### ISSUE TITLE
how to call static methods

### ISSUE THREAD

**Issue by dreamorosi** [aws-samples/aws-cdk-stack-builder-tool#2]
Hi, how can I call static methods on constructs?

For example, say I want to import a Lambda Layer using its ARN rather than creating one from scratch, in CDK I would do this:

```ts
const powertoolsLayer = lambda.LayerVersion.fromLayerVersionArn(
      this,
      'PowertoolsLayer',
      `arn:aws:lambda:${cdk.Stack.of(this).region}:094274105915:layer:AWSLambdaPowertoolsTypeScript:23`
    );
```

How can I do this in the tool?

**Comment by spugachev** [comment]
Hi, 

You cannot create a layer by using `fromLayerVersionArn` directly. However, if you select a Lambda function, then navigate to the 'layers' property, you have the option to utilize the `fromLayerVersionArn` function from there.

By the way. We are considering adding Lambda code editor that utilizes Powertools by default
